# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.knots_list = QtWidgets.QListView(self.centralwidget)
        self.knots_list.setGeometry(QtCore.QRect(20, 80, 161, 421))
        self.knots_list.setObjectName("knots_list")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(200, 30, 571, 331))
        self.graphicsView.setObjectName("graphicsView")
        self.open_folder = QtWidgets.QPushButton(self.centralwidget)
        self.open_folder.setGeometry(QtCore.QRect(40, 30, 121, 41))
        self.open_folder.setObjectName("open_folder")
        self.previous_image = QtWidgets.QPushButton(self.centralwidget)
        self.previous_image.setGeometry(QtCore.QRect(200, 370, 121, 41))
        self.previous_image.setObjectName("previous_image")
        self.next_image = QtWidgets.QPushButton(self.centralwidget)
        self.next_image.setGeometry(QtCore.QRect(650, 370, 121, 41))
        self.next_image.setObjectName("next_image")
        self.knot_select = QtWidgets.QCheckBox(self.centralwidget)
        self.knot_select.setGeometry(QtCore.QRect(210, 420, 87, 20))
        self.knot_select.setObjectName("knot_select")
        self.split_selector = QtWidgets.QCheckBox(self.centralwidget)
        self.split_selector.setGeometry(QtCore.QRect(210, 450, 87, 20))
        self.split_selector.setObjectName("split_selector")
        self.partial_selector = QtWidgets.QCheckBox(self.centralwidget)
        self.partial_selector.setGeometry(QtCore.QRect(210, 480, 87, 20))
        self.partial_selector.setObjectName("partial_selector")
        self.knot_slider = QtWidgets.QSlider(self.centralwidget)
        self.knot_slider.setGeometry(QtCore.QRect(280, 420, 160, 22))
        self.knot_slider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.knot_slider.setObjectName("knot_slider")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(420, 380, 118, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.split_slider = QtWidgets.QSlider(self.centralwidget)
        self.split_slider.setGeometry(QtCore.QRect(280, 450, 160, 22))
        self.split_slider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.split_slider.setObjectName("split_slider")
        self.partial_slider = QtWidgets.QSlider(self.centralwidget)
        self.partial_slider.setGeometry(QtCore.QRect(280, 480, 160, 22))
        self.partial_slider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.partial_slider.setObjectName("partial_slider")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 37))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.open_folder.setText(_translate("MainWindow", "Open Folder"))
        self.previous_image.setText(_translate("MainWindow", "Previous Image"))
        self.next_image.setText(_translate("MainWindow", "Next Image"))
        self.knot_select.setText(_translate("MainWindow", "Knots"))
        self.split_selector.setText(_translate("MainWindow", "Splits"))
        self.partial_selector.setText(_translate("MainWindow", "Partial"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
